config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :messages do
    member do
      get "like" => "messages#upvote"
      get "dislike" => "messages#downvote"
      end
    collection do
      get :recent
      get :oldest
      get :upvoted
      get :downvoted
    end
  	resources :comments
  end
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end
# Comments belong to both users and messages.

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
  mount_uploader :video, VideoUploader
  acts_as_votable
  scope :recent, -> { order(created_at: :desc) }
  scope :oldest, -> { order(created_at: :asc) }
  scope :upvoted, -> { order(:cached_votes_up => :desc) }
  scope :downvoted, -> { order(:cached_votes_down => :desc) }



end
#Allows filterable options allow's videos to be uploaded and allow comments on messages. This file also attributes messages to users.

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter       

end
# File attributes messages and comments to users, allows users to upload avatar, and adds devise functionality to user. 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :avatar])
  end
end
#Whitelisting several data types with devise.

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id
  #allowing comments to save and redirecting to the message page otherwise it creates a new comment option.
    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end
  #allows comments to edit.
  def edit
  end

#Allows comments to update if the content params are satisfied updates and redirects to the message otherwise redirects to edit.
  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
  end
end
  #deletes comments
  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
    def find_message
      @message = Message.find(params[:message_id])
    end

    def find_comment
      @comment = @message.comments.find(params[:id])
    end
  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :upvote, :downvote, :destroy]
  before_action :authenticate_user!, except: [:index , :recent, :oldest, :upvoted, :downvoted, :show]

  def index
    @messages = Message.all
  end

  def recent
    @messages = Message.recent
    render action: :index
  end

  def oldest
    @messages = Message.oldest
    render action: :index
  end

  def upvoted
    @messages = Message.upvoted
    render action: :index
  end

  def downvoted
    @messages = Message.downvoted
    render action: :index
  end

  def show
  end

  def upvote
    @message.upvote_from current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @message.downvote_from current_user
    redirect_back(fallback_location: root_path)
  end

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  private
  def self.sort_by(sort_param)
    if %w(recent oldest downvoted upvoted).include? sort_param
      send sort_param
    else
      all
    end
  end

    def message_params
      params.require(:message).permit(:title, :description, :video)
    end

    def find_message
      @message = Message.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p>Posted By <%= comment.user.username %> <%= time_ago_in_words(comment.created_at) %> ago</p>
<% if user_signed_in? %>
  <% if comment.user_id == current_user.id %>
    <%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
    <%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are You Sure" } %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




<nav class="navbar navbar-custom navbar-inverse navbar-fixed-top" id="mynav" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Message Board", root_path, class: "navbar-brand mybrand" %>
    </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <li><%= link_to "New Message", new_message_path %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>


    </ul>
    <ul class = "nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li><a>Logged In As: <%= current_user.username %></a></li>
      <li><p><%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav navbar-text" %></p></li>
    <% end %>
    </ul>
  </div>

  </div>

</nav>
<div class="main-background">
<div class ="container" id="main-index">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
</div>
</div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class = "container-fluid">
  <div class = "col-md-12">
<%= simple_form_for @message do |f| %>
  <%= f.input :title, class: "text-center", label: "Message Title" %>
  <%= f.input :description %>
  <%= f.file_field :video %>
  <%= f.button :submit %>
<% end %>
</div>

</div>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class = "row">



  <div class="card-header box">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <%= link_to "Recent", recent_messages_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Oldest", oldest_messages_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Upvoted", upvoted_messages_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Downvoted", downvoted_messages_path, class: "nav-link active" %>
      </li>
    </ul>
  </div>
<% @messages.each do |m| %>

<div class = "container-fluid col-md-6 col-sm-12 custom-box card text-center">

<div class = "card-header box">
  <h2><%= link_to m.title, message_path(m) %></h2>
  <p>Posted By: <%= image_tag m.user.avatar.url, size:25, class: 'img-rounded' %> <%= m.user.username %></p>
  <h6><p><%= time_ago_in_words(m.created_at) %> ago </p></h6>
</div>
<div class = "card-body box">
  <p><%= m.description.truncate(30) %>... </p>
  <%= link_to "View Message", message_path(m), class: "btn btn-default btn-primary" %>
</div>

<div class = "caption card-footer box" style = "text=align:center;">
  <%= link_to like_message_path(m), method: :get, remote: true, class: "like", method: :put do %>
  <button type="button" class="btn" aria-label="Left Align">
    <span class="glyphicon glyphicon-chevron-up glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= m.get_upvotes.size %></span>
  </button>
  <% end %>

  <%= link_to dislike_message_path(m), method: :get, remote: true, class: "like", method: :put do %>
  <button type="button" class="btn" aria-label="Left Align">
    <span class="glyphicon glyphicon-chevron-down glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= m.get_downvotes.size %></span>
  </button>
  <% end %>


</div>

</div>

<% end %>


</div>


<!-- <%= link_to "New Message", new_message_path %> -->

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<div class = "container-fluid" id = "message-show">
  <div class = "col-md-12">


  <div class = "jumbotron">
    <h2><%= @message.title %>
    </h2>
  </div>

Posted By: <%= image_tag @message.user.avatar.url, size:25, class: 'img-rounded' %> <%= @message.user.username %>

   <p><%= time_ago_in_words(@message.created_at) %> ago</p><br>

   <div class ="text-center">
<% if @message.video? %>
  <% if @message.video_url.include? "jpg" or @message.video_url.include? "jpeg" or @message.video_url.include? "gif" or @message.video_url.include? "png" %>
  <%= image_tag @message.video_url %>
  <% else %>
  <%= video_tag @message.video_url, :controls => true %>
<% end %>
<% end %>
</div>
<div class = "background">
  <p><%= @message.description %></p>
</div>
<div class = "caption" style = "text=align:center;">
  <%= link_to like_message_path(@message), method: :get, remote: true, class: "like", method: :put do %>
  <button type="button" class="btn" aria-label="Left Align">
    <span class="glyphicon glyphicon-chevron-up glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= @message.get_upvotes.size %></span>
  </button>
  <% end %>

  <%= link_to dislike_message_path(@message), method: :get, remote: true, class: "like", method: :put do %>
  <button type="button" class="btn" aria-label="Left Align">
    <span class="glyphicon glyphicon-chevron-down glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= @message.get_downvotes.size %></span>
  </button>
  <% end %>


</div>

<h3>Comments:</h3>
<%= render @message.comments %>

<h3>Leave a comment:</h3>
<%= render 'comments/form' %>

<%= link_to "Back", root_path, class: "btn" %>
<% if user_signed_in? %>
  <% if @message.user_id == current_user.id %>
    <%= link_to "Edit", edit_message_path(@message), class: "btn" %>
    <%= link_to "Delete", message_path(@message), class: "btn", method: :delete, data: { confirm: "Are You Sure" } %>
<% end %>
<% end %>
</div>
</div>